name: Deploy Cloud Function (Dev)

on:
  push:
    branches:
      - dev
    paths:
      - ".github/workflows/deploy-cloud-function-dev.yml"
      - "main.py"
      - "requirements.txt"
      - "tests/**"
      - "utils/**"
  workflow_dispatch:
    inputs:
      PROJECT_NAME:
        description: "GCP Project Name"
        required: false
        default: "insightsprod"
      AUDIT_DATASET_NAME:
        description: "Audit Dataset Name"
        required: false
        default: "edm_insights_metadata"
      SLACK_CHANNEL_ID:
        description: "Slack Channel ID"
        required: false
        default: "C065MG2L63U"
      SLACK_API_TOKEN:
        description: "Slack API Token"
        required: false
        default: "xoxb-xxx-xxx"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Development

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      env:
        PROJECT_NAME: ${{ github.event.inputs.PROJECT_NAME || vars.PROJECT_NAME }}
        AUDIT_DATASET_NAME: ${{ github.event.inputs.AUDIT_DATASET_NAME || vars.AUDIT_DATASET_NAME }}
        SLACK_CHANNEL_ID: ${{ github.event.inputs.SLACK_CHANNEL_ID || vars.SLACK_CHANNEL_ID }}
        SLACK_API_TOKEN: ${{ github.event.inputs.SLACK_API_TOKEN || secrets.SLACK_API_TOKEN }}
      run: pytest

    - id: "auth"
      uses: "google-github-actions/auth@v2"
      with:
        credentials_json: "${{ secrets.GCP_SA_KEY }}"

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Deploy Cloud Function
      env:
        PROJECT_NAME: ${{ github.event.inputs.PROJECT_NAME || vars.PROJECT_NAME }}
        AUDIT_DATASET_NAME: ${{ github.event.inputs.AUDIT_DATASET_NAME || vars.AUDIT_DATASET_NAME }}
        SLACK_CHANNEL_ID: ${{ github.event.inputs.SLACK_CHANNEL_ID || vars.SLACK_CHANNEL_ID }}
        SLACK_API_TOKEN: ${{ github.event.inputs.SLACK_API_TOKEN || secrets.SLACK_API_TOKEN }}
      run: |
        gcloud functions deploy data-latency-alerts-dev \
          --region=us-central1 \
          --memory=512M \
          --timeout=3600 \
          --concurrency=1 \
          --max-instances=10 \
          --source=. \
          --trigger-http \
          --runtime=python311 \
          --entry-point=latency_alert \
          --allow-unauthenticated \
          --set-env-vars PROJECT_NAME=$PROJECT_NAME,AUDIT_DATASET_NAME=$AUDIT_DATASET_NAME,SLACK_CHANNEL_ID=$SLACK_CHANNEL_ID,SLACK_API_TOKEN=$SLACK_API_TOKEN
